#!/usr/bin/with-contenv bash

# Run mediaserver as ${COMPANY_NAME} user
echo "Launching mediaserver"
exec s6-setuidgid ${COMPANY_NAME} /bin/bash -c '/opt/${COMPANY_NAME}/mediaserver/bin/mediaserver -e'

# Run mediaserver as root user
# exec /opt/${COMPANY_NAME}/mediaserver/bin/mediaserver -e
