#!/usr/bin/with-contenv bash

### Set directory ownership permissions
echo "init-nx-permissions : COMPANY_NAME = ${COMPANY_NAME}"

# Test for current owner and only change if not currently owned by ${COMPANY_NAME}
# Blindly changing permissions on many files takes too long
# If files previously existed the permissions may have to be manually corrected

# /config (recursive)
if [[ ! "$(stat -c %U /config)" = "${COMPANY_NAME}" ]]
then
    echo "Changing ownership on /config"
    chown --verbose --recursive ${COMPANY_NAME}:${COMPANY_NAME} /config
fi

# /media (recursive)
if [[ ! "$(stat -c %U /media)" = "${COMPANY_NAME}" ]]
then
    echo "Changing ownership on /media"
    chown --verbose --recursive ${COMPANY_NAME}:${COMPANY_NAME} /media
fi

# /opt/${COMPANY_NAME}/mediaserver/bin
if [[ ! "$(stat -c %U /opt/${COMPANY_NAME}/mediaserver/bin)" = "${COMPANY_NAME}" ]]
then
    echo "Changing ownership on ../mediaserver/bin"
    chown --verbose ${COMPANY_NAME}:${COMPANY_NAME} /opt/${COMPANY_NAME}/mediaserver/bin
fi

# /opt/${COMPANY_NAME}/mediaserver/bin/external.dat
if [[ ! "$(stat -c %U /opt/${COMPANY_NAME}/mediaserver/bin/external.dat)" = "${COMPANY_NAME}" ]]
then
    echo "Changing ownership on ../mediaserver/bin/external.dat"
    chown --verbose ${COMPANY_NAME}:${COMPANY_NAME} /opt/${COMPANY_NAME}/mediaserver/bin/external.dat
fi
