version: "3.7"

services:
  nxmeta:
    image: nxmeta
    container_name: nxmeta-zfs
    build: .
    restart: unless-stopped
    environment:
      - TZ=Americas/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - nxmeta_config:/config
      - nxmeta_media:/media
      - nxmeta_archive:/archive
    network_mode: host

volumes:
  nxmeta_config:
    driver_opts:
      type: none
      device: /mnt/nxmeta/config
      o: bind
  nxmeta_media:
    driver_opts:
      type: none
      device: /mnt/nxmeta/media
      o: bind
  nxmeta_archive:
    driver_opts:
      type: none
      device: /mnt/nxmeta/archive
      o: bind
        
# sudo zfs create -o mountpoint=/mnt/nxmeta ssdpool/nxmeta
# sudo zfs create -o mountpoint=/mnt/nxmeta/config ssdpool/nxmeta/config
# sudo zfs create -o mountpoint=/mnt/nxmeta/media ssdpool/nxmeta/media
# sudo zfs create -o mountpoint=/mnt/nxmeta/archive hddpool/nxmeta/archive
# docker-compose --file docker-compose-zfs.yml up --detach
