name: "Update Docker Hub Description"

on:
  push:
    branches: [ main ]
    paths: [HubREADME.md, .github/workflows/DockerHubDescription.yml]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  description:
    name: "Update Docker Hub Description"
    runs-on: ubuntu-latest

    strategy:
      # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        repos:
          [
            ptr727/nxgo,
            ptr727/nxgo-lsio,
            ptr727/nxmeta,
            ptr727/nxmeta-lsio,
            ptr727/nxwitness,
            ptr727/nxwitness-lsio,
            ptr727/dwspectrum,
            ptr727/dwspectrum-lsio,
            ptr727/wisenetwave,
            ptr727/wisenetwave-lsio,
          ]

    steps:
      # https://github.com/actions/checkout
      - name: "Checkout Code"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/docker-hub-description
      # Access tokens cannot update readme.md, we have to use the real password
      # Use a matrix to update descriptions of all repos
      - name: "Update Docker Hub Description"
        # Skip pull requests
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ matrix.repos }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./HubREADME.md
